# Generated by Django 4.1.3 on 2022-12-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=60)),
                ('escuela', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinturon', models.CharField(max_length=12)),
                ('edad', models.IntegerField(max_length=2)),
                ('peso', models.IntegerField(max_length=3)),
            ],
        ),
    ]
