# Generated by Django 4.1.3 on 2022-12-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPF', '0002_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='peso',
        ),
    ]
