# Generated by Django 4.1.3 on 2022-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPF', '0003_remove_nivel_edad_remove_nivel_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaCompanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='modalidad',
        ),
    ]
